#config_version=5

player_vars:
  theme_mode_timer_variable:
    initial_value: 0
    value_type: int

  has_current_thememode:      # tracks if/when player is successful completing themed mode
    initial_value: 0
    value_type: int
  has_a_highscore:
    initial_value: 0
    value_type: int

  # track all themed mode statuses
  # TODO: setting longpour, quarters, strikeout to 1 so I can test volumechug and trojankeg modes quicker
  has_longpour:
    initial_value: 0
    value_type: int
  has_quarters:
    initial_value: 0
    value_type: int
  has_strikeout:
    initial_value: 0
    value_type: int
  has_volumechug:
    initial_value: 0
    value_type: int
  has_trojankeg:
    initial_value: 0
    value_type: int
  has_dasboot:
    initial_value: 0
    value_type: int
  
  # end-of-ball bonuses
  bonus_numquarters:
    initial_value: 0
    value_type: int
  bonus_numhjs:
    initial_value: 0
    value_type: int
  bonus_numbjs:
    initial_value: 0
    value_type: int
  bonus_numzjs:
    initial_value: 0
    value_type: int
  bonus_numstrikeouts:
    initial_value: 0
    value_type: int
  bonus_numramps:
    initial_value: 0
    value_type: int
  bonus_numchance:    # this is used as the overall multiplier for bonus
    initial_value: 1
    value_type: int

  # end-of-ball subtotals
  bonus_sub_quarters:
    initial_value: 0
    value_type: int
  bonus_sub_hjs:
    initial_value: 0
    value_type: int
  bonus_sub_bjs:
    initial_value: 0
    value_type: int
  bonus_sub_zjs:
    initial_value: 0
    value_type: int
  bonus_sub_strikeouts:
    initial_value: 0
    value_type: int
  bonus_sub_ramps:
    initial_value: 0
    value_type: int    
  bonus_total:
    initial_value: 0
    value_type: int

  bonus_canceled:
    initial_value: 0
    value_type: int

  pts_kicker_mode:
    initial_value: 200000
    value_type: int
  pts_kicker_rimrules:
    initial_value: 100000
    value_type: int
  pts_hj:
    initial_value: 12000
    value_type: int
  pts_bj:
    initial_value: 10000
    value_type: int
  pts_zj:
    initial_value: 15000
    value_type: int
  pts_chance:
    initial_value: 25000
    value_type: int
  pts_special:
    initial_value: 50000
    value_type: int
  pts_take_hit:
    initial_value: 69000
    value_type: int
  pts_chug_beer:
    initial_value: 69000
    value_type: int
  pts_do_shot:
    initial_value: 69000
    value_type: int
  pts_quarters:
    initial_value: 75000
    value_type: int
  pts_tgt_ramp_boot_left:
    initial_value: 50000
    value_type: int
  pts_tgt_ramp_boot_right:
    initial_value: 50000
    value_type: int
  pts_tgt_rimrules:
    initial_value: 50000
    value_type: int
  pts_ramp_boot:
    initial_value: 100000
    value_type: int
  pts_ramp_upf:
    initial_value: 100000
    value_type: int
  pts_horseshoe:
    initial_value: 1000000
    value_type: int
  pts_tavern:
    initial_value: 25000
    value_type: int
  pts_upf_tgt_left:
    initial_value: 40000
    value_type: int
  pts_upf_tgt_right:
    initial_value: 40000
    value_type: int
  pts_rnd:
    initial_value: 10000    # used for pops and slings - these will have some multiple of 10 points (up to 9x) added. To randomize lower two digits of score
    value_type: int
  
  # bonuses & awards
  
  pts_upf_bonus1:
    initial_value: 1000000
    value_type: int
  pts_upf_bonus2:
    initial_value: 3500000
    value_type: int
  pts_upf_hammered:
    initial_value: 5000000
    value_type: int
  pts_spell_beer:
    initial_value: 125000
    value_type: int
  pts_spell_munich:
    initial_value: 150000
    value_type: int 
  pts_skillshot_full:
    initial_value: 500000
    value_type: int
  pts_skillshot_partial:
    initial_value: 100000
    value_type: int
  pts_multiball:
    initial_value: 3000000
    value_type: int

  # Longpour
  pts_longpour_ramps_themed:
    initial_value: 500000
    value_type: int
  pts_longpour_success:
    initial_value: 10000000
    value_type: int
  pts_longpour_partial:
    initial_value: 5000000
    value_type: int

  # Quarters
  pts_quarters_themed:
    initial_value: 500000
    value_type: int
  pts_quarters_success:
    initial_value: 10000000
    value_type: int
  pts_quarters_partial:
    initial_value: 5000000
    value_type: int

  # Strikeout
  pts_take_hit_themed:
    initial_value: 150000
    value_type: int
  pts_chug_beer_themed:
    initial_value: 150000
    value_type: int
  pts_do_shot_themed:
    initial_value: 150000
    value_type: int
  pts_strikeout_complete:
    initial_value: 150000
    value_type: int
  pts_strikeout_complete_themed:
    initial_value: 1000000
    value_type: int
  pts_strikeout_success:
    initial_value: 10000000
    value_type: int
  pts_strikeout_partial:
    initial_value: 5000000
    value_type: int

  # Volume Chug
  # pts_ramp_tavern_themed already declared above
  pts_pops_themed:
    initial_value: 250000
    value_type: int
  # pts_ramp_boot_themed already declared above
  pts_volumechug_bonus:
    initial_value: 10000000
    value_type: int
  pts_volumechug_success:
    initial_value: 25000000
    value_type: int
  pts_volumechug_partial:
    initial_value: 12500000
    value_type: int

  # Trojan Keg
  pts_hj_themed:
    initial_value: 120000
    value_type: int
  pts_bj_themed:
    initial_value: 100000
    value_type: int
  pts_zj_themed:
    initial_value: 150000
    value_type: int
  pts_kicker_mode_themed:
    initial_value: 500000
    value_type: int
  pts_trojankeg_bonus:
    initial_value: 10000000
    value_type: int
  pts_trojankeg_success:
    initial_value: 30000000
    value_type: int
  pts_trojankeg_partial:
    initial_value: 15000000
    value_type: int

  # Das Boot
  pts_dasboot_boot_bonus:
    initial_value: 50000000
    value_type: int
  pts_dasboot_target_bonus:
    initial_value: 10000000
    value_type: int
  pts_dasboot_success:
    initial_value: 50000000
    value_type: int
  dasboot_bonus_multiplier:
    initial_value: 5
    value_type: int
    
  # bonus calculation values
  pts_quarters_bonus:
    initial_value: 7500
  pts_hjs_bonus:
    initial_value: 1200
  pts_bjs_bonus:
    initial_value: 1000
  pts_zjs_bonus:
    initial_value: 1500
  pts_strikeouts_bonus:
    initial_value: 15000
  pts_ramps_bonus:
    initial_value: 10000

  # bonus calculations for text on slides
  dasboot_bonustext_monkeychug:
    initial_value: 0
    value_type: int
  dasboot_bonustext_upfbonus1:
    initial_value: 0
    value_type: int
  dasboot_bonustext_upfbonus2:
    initial_value: 0
    value_type: int
  dasboot_bonustext_hammered:
    initial_value: 0
    value_type: int
  dasboot_bonustext_spellbeer:
    initial_value: 0
    value_type: int
  dasboot_bonustext_spellmunich:
    initial_value: 0
    value_type: int
  dasboot_bonustext_strikeoutcomplete:
    initial_value: 0
    value_type: int

  # additional point variations
  flipperflop_pts:
    initial_value: 5000000
    value_type: int

  # track if we are displaying upf bonus slide. This is used to enforce order of Monkeychug bonus slide/sound and upf bonus slide/sound
  is_slide_upf1_queued:
    initial_value: 0
    value_type: int
  is_slide_upf2_queued:
    initial_value: 0
    value_type: int
  is_slide_hammered_queued:
    initial_value: 0
    value_type: int
  is_slide_monkeychug_active:
    initial_value: 0
    value_type: int

  # track if we are displaying pong sink video slide
  is_showing_pongsink_slide:
    initial_value: 0
    value_type: int

  is_welcome_played:
    initial_value: 0
    value_type: int

  is_skillshot_active:
    initial_value: 0
    value_type: int