#config_version=5

switches:
  # Upper Switch PCB: A0
  # Bank A (J2) (A0-B0)

  # new mapping
  s_paddle_d2:
    number: A0-B0-5   # n -> o pre update
  s_paddle_l:
    number: A0-B0-4   # k -> k pre update
  s_paddle_e:
    number: A0-B0-0   # o -> d pre update


  #s_drinko_bang:
  #  number: A0-B0-6
  s_plunger_lane_exit:
    number: A0-B0-7
    type: NC
    tags: playfield_active
  # Bank B (J6) (A0-B1)
  s_pongcup1:
    number: A0-B1-1
    type: NC
    ignore_window_ms: 750
  s_pongcup2:
    number: A0-B1-0
    type: NC
    ignore_window_ms: 750
  s_pop_lower:
    number: A0-B1-2
  s_pop_upper_left:
    number: A0-B1-3
  s_pop_upper_right:
    number: A0-B1-4
  s_flipper_left:
    number: A0-B1-5
    tags: left_flipper
  s_flipper_right:
    number: A0-B1-6
    tags: right_flipper
  s_start:
    number: A0-B1-7
    tags: start
  
  # Left Switch PCB (A1)
  # Bank A (J2) (A1-B0)
  s_drain:
    number: A1-B0-0
  s_slingshot_left:
    number: A1-B0-1
  s_laneleft_inner:
    number: A1-B0-2
  s_laneleft_outer:
    number: A1-B0-3
  s_slingshot_quarters:
    number: A1-B0-4
  s_quarters:
    number: A1-B0-5
  s_take_hit:
    number: A1-B0-6
    type: NC
  s_chug_beer:
    number: A1-B0-7
    type: NC
  # Bank B (J6) (A1-B1)
  s_tgt_ramp_boot_left:
    number: A1-B1-0
  s_tavern_exit:              # currently not implemented (switch wire NOT installed)
    number: A1-B1-1
    type: NC
  s_tavern_spinner:
    number: A1-B1-2
    tags: playfield_active
  s_kicker_rimrules:
    number: A1-B1-3
    ignore_window_ms: 500
    type: NC
  s_do_shot:
    number: A1-B1-4
    type: NC
  s_tgt_ramp_boot_right:
    number: A1-B1-5
  s_target_rimrules:
    number: A1-B1-6
  s_orbit_entry:              # currently not implemented (switch wire is installed tho)
    number: A1-B1-7

  # Right Switch PCB (A2)
  # Bank A (J2) (A2-B0)
  s_popo:
    number: A2-B0-0
    tags: playfield_active
  s_open1:
    number: A2-B0-1
    tags: playfield_active
  s_open2:
    number: A2-B0-2
    tags: playfield_active
  s_kicker_mode:
    number: A2-B0-3
    ignore_window_ms: 500
    type: NC
  s_chance: 
    number: A2-B0-4
    tags: playfield_active
  s_special:
    number: A2-B0-5
  s_open3:             # currently not used
    number: A2-B0-6
  s_orbit_exit:               # currently not implemented (switch wire is installed tho)
    number: A2-B0-7
  # Bank B (J6) (A2-B1)
  s_slingshot_right:
    number: A2-B1-0
  s_laneright_inner:
    number: A2-B1-1
  s_laneright_outer:
    number: A2-B1-2
  s_trough3:
    number: A2-B1-3
    type: NC
  s_trough1:
    number: A2-B1-4
    type: NC
  s_trough2:
    number: A2-B1-5
    type: NC
  s_trough_eject:
    number: A2-B1-6
  s_plunger_lane:
    number: A2-B1-7
  
  # UpperPF Switch PCB (A3)
  # Bank A (J2) (A3-B0)  
  
  
  # Bank B (J6) (A3-B1) 
  s_ramp_upf_entry:
    number: A3-B1-0
    type: NC
  s_ramp_upf_exit:
    number: A3-B1-1
    type: NC
  s_horseshoe:
    number: A3-B1-2
    type: NC
  s_upf_tgt_left:
    number: A3-B1-3
  s_upf_tgt_right:
    number: A3-B1-4
  s_diverter:
    number: A3-B1-5
    type: NC
  s_adult:
    number: A3-B1-6
  
  
  
  
  
  
  
  
  
  
